name: webvuln
description: "Web vulnerabilities scanner."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.1.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  line_icons: ^2.0.3
  icons_plus: ^5.0.0
  fluentui_system_icons: ^1.1.218
  dio: ^5.3.3
  get: ^4.6.6
  checkbox_grouped: ^2.0.0
  font_awesome_flutter: ^10.6.0
  ionicons: ^0.2.2
  percent_indicator: ^4.2.3
  easy_loader: ^2.0.0
  flutter_easyloading: ^3.0.5
  intl: ^0.18.1
  group_button: ^5.3.3
  pluto_grid: ^7.0.2
  data_table_2: ^2.5.9
  syncfusion_flutter_gauges: ^24.1.43
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^24.1.43+1
  pie_chart: ^5.3.2
  dropdown_button2: ^2.3.9
  lite_rolling_switch: ^1.0.1
  flutter_advanced_switch: ^3.0.1
  flutter_resizable_container: ^0.1.2
  dropdown_search: ^5.0.6
  flutter_expandable_table: ^2.0.1
  decorated_dropdownbutton: ^0.0.3
  flutter_dropdown: ^1.0.1+hotfix.1
  calendar_date_picker2: ^0.5.3
  desktop_window: ^0.4.0
  preload_page_view: ^0.2.0
  data_tables: ^1.4.0
  just_the_tooltip: ^0.0.12
  google_fonts: ^6.1.0
  file_picker: ^6.1.1
  web_socket_channel: ^2.4.0
  pdf: ^3.10.7
  easy_folder_picker: ^1.3.1
  filepicker_windows: ^2.0.11
  process_run: ^0.13.3
  flutter_isolate: ^2.0.4
  get_it: ^7.6.4
  injectable: ^2.3.2
  flutter_dotenv: ^5.1.0
  external_path: ^1.0.3
  flex_color_scheme: ^7.3.1
  provider: ^6.1.1
  ini: ^2.1.0

  path: any
  path_provider: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  assets:
    - lib/assets/
  uses-material-design: true

window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
